# Generated by Django 3.1.1 on 2020-09-20 12:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200920_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='like_datetime',
        ),
        migrations.AddField(
            model_name='like',
            name='like_date',
            field=models.DateField(default=datetime.date(2020, 9, 20)),
        ),
    ]
