# Generated by Django 3.1.1 on 2020-09-20 15:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200920_1835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author_name',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='like',
            name='like_date',
            field=models.DateField(default=datetime.datetime(2020, 9, 20, 15, 37, 38, 554180, tzinfo=utc)),
        ),
    ]
