# Generated by Django 3.1.1 on 2020-09-20 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20200920_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='amount_of_likes',
        ),
    ]
